base_url = "https://vesla0x1.eth.limo"
title = "vesla0x1"
author = "vesla0x1"
description = "Blockchain development and security"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = true
taxonomies = [
    { name = "tags" },
    { name = "home", paginate_by = 6, paginate_path = "" },
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/vesla0x1" },
    { name = "Twitter", icon = "twitter", url = "https://twitter.com/vesla0xfa" },
    { name = "Email", icon = "email", url = "mailto:vesla0x1@gmail.com" },
    { name = "Feed", icon = "rss", url = "/atom.xml" },
]

sections = [
    { name = "home", path = "/" },
    { name = "audits", path = "/audits" },
    { name = "articles", path = "/articles" },
    { name = "coding", path = "/coding" },
    { name = "achievements", path = "/achievements" },
    { name = "about", path = "/about" },
    { name = "tags", path = "/tags" },
]

footer_copyright = "© 2024 vesla0x1"
not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"